# Generated by Django 4.2.1 on 2023-05-08 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('cod_region', models.CharField(max_length=40)),
                ('cod_comuna', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=20)),
                ('papellido', models.CharField(max_length=20)),
                ('sapellido', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('cod_comuna', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ventas.comuna')),
            ],
            options={
                'db_table': 'harrys_persona',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.question')),
            ],
        ),
    ]
