# Generated by Django 4.1.7 on 2023-06-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente_empleado_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='local',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
