# Generated by Django 4.1.7 on 2023-06-23 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_empleado_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='turno',
        ),
    ]
