# Generated by Django 4.1.7 on 2023-06-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_remove_proveedor_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.CharField(blank=True, choices=[('accesorios', 'Accesorios'), ('carroceria', 'Carroceria'), ('motor', 'Motor')], max_length=10, null=True),
        ),
    ]
